#KV_PATH varible is defined before

KV_SRC=$(wildcard $(KV_PATH)/*.cc)                                                 
KV_DB_LIB_PATH=-L$(KV_PATH)/lib                                                    
KV_DB_LIB=-lleveldb -lpthread -lsnappy                                             
KV_DB_INC=-I$(KV_PATH)/include
